#server:
#  port: 9006
#eureka:
#  client:
#    registerWithEureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

#spring:
#  application:
#    name: demo-redission

# Redis数据库索引（默认为0）
#spring.redis.database=1
# Redis服务器地址
#spring.redis.host=192.168.3.3
# Redis服务器连接端口
#spring.redis.port=6379
# Redis服务器连接密码（默认为空）
#spring.redis.password=test123

# redisson lock
#redisson:
#   address: 39.104.170.221:6379
#redisson:
#  password: 123456
