package com.qiangge.webservice.client.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2019-03-25T19:12:49.689+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebService(targetNamespace = "http://service.webservicedemo.qiangge.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getName", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getName(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebMethod
    @RequestWrapper(localName = "getAlLUser", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetAlLUser")
    @ResponseWrapper(localName = "getAlLUserResponse", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetAlLUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qiangge.webservice.client.wsdl.User> getAlLUser();

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.webservicedemo.qiangge.com/", className = "com.qiangge.webservice.client.wsdl.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.qiangge.webservice.client.wsdl.User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
