
package com.qiangge.webservice.client.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2019-03-25T19:12:49.523+08:00
 * Generated source version: 3.1.18
 * 
 */
public final class UserService_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.webservicedemo.qiangge.com/", "UserServiceImplService");

    private UserService_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserServiceImplService ss = new UserServiceImplService(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServiceImplPort();  
        
        {
        System.out.println("Invoking getName...");
        java.lang.String _getName_userId = "";
        java.lang.String _getName__return = port.getName(_getName_userId);
        System.out.println("getName.result=" + _getName__return);


        }
        {
        System.out.println("Invoking getAlLUser...");
        java.util.List<com.qiangge.webservice.client.wsdl.User> _getAlLUser__return = port.getAlLUser();
        System.out.println("getAlLUser.result=" + _getAlLUser__return);


        }
        {
        System.out.println("Invoking getUser...");
        java.lang.String _getUser_arg0 = "";
        com.qiangge.webservice.client.wsdl.User _getUser__return = port.getUser(_getUser_arg0);
        System.out.println("getUser.result=" + _getUser__return);


        }

        System.exit(0);
    }

}
